version: '3.8'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product_cart:
    image: enot42/product-cart
    container_name: product-cart
    hostname: product-cart
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '6080:6080'
